config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :list_youtubes
  resources :ajaxs
  resources :video_channels
  resources :video_onlys
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/ajaxs_controller.rb
require 'net/http'

class AjaxsController < ApplicationController
  def index
    uri = URI(params[:link])
    @result = Net::HTTP.get_response(uri)
    # respond_to do |format|
    #   format.html
    #   format.json{render json: {content: @result.body.html_safe}}
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'net/http'

class HomeController < ApplicationController
  def index
  end
end

app/controllers/list_youtubes_controller.rb
class ListYoutubesController < ApplicationController
end

app/controllers/video_channels_controller.rb
class VideoChannelsController < ApplicationController
  def index
  end
end

app/controllers/video_onlys_controller.rb
class VideoOnlysController < ApplicationController
  def index
  end
end

app/helpers/ajaxs_helper.rb
module AjaxsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_youtubes_helper.rb
module ListYoutubesHelper
end

app/helpers/video_channels_helper.rb
module VideoChannelsHelper
end

app/helpers/video_onlys_helper.rb
module VideoOnlysHelper
end

app/views/ajaxs/index.html.erb
<%= @result.body.html_safe %>

app/views/home/index.html.erb
<div class="contanier">
  <div class="col-md-8 ">
    <ul class="list">
      <li><a href="<%= list_youtubes_path %>">List Youtube</a></li>
      <li><a href="<%= video_channels_path %>">Video Channel</a></li>
      <li><a href="<%= video_onlys_path %>">Video only</a></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Youtube</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <a href="<%= root_path %>">Home</a>
    </div>
    <%= yield %>
  </body>
</html>

app/views/list_youtubes/index.html.erb
<div class="contanier">
  <div class="col-md-12">
    <input name="list_youtube" style="width: 800px;" />
    <br>
    <button id="action" style="padding: 10px; margin: auto">Get list</button>
    <button id="getlink" style="padding: 10px; margin: auto">Get link</button>
    /*<button id="upload" style="padding: 10px; margin: auto">upload</button>*/
  </div>
</div>
<div id='log'>
  
</div>
<div class="contanier">
  <div class="col-md-12 row">
    <div class="col-md-6">
      <div id="list_youtubes" hidden=""></div>
    </div>
   <div class="col-md-6">
      <div id="youtube_details" hidden=""></div>
    </div>
  </div>
</div>

app/views/video_channels/index.html.erb
<div class="col-md-8">
  <button id='action2'>Action2</button>
  <button id="getlink" style="padding: 10px; margin: auto">Get link</button>
  <br>
  <br>

  <textarea id="text_area" cols=80 rows=10>
    
  </textarea>
  <div id='log'>
  
</div>
</div>
<div id="list_youtubes" hidden="">
</div>
<div id="youtube_details" hidden=""></div>

app/views/video_onlys/index.html.erb
<div class="col-md-4">
  <div id="list_url">
    
  </div>
  <button id="btn_add">ADD</button>
</div>
<div class="col-md-6">
<button id="video_action">Action</button>
<button id="video_getlink">Get Link</button>
<div id='log'></div>
</div>
<div id="youtube_details" hidden></div>